apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2020-09-12T07:14:22Z
  labels:
    docker-registry: default
  name: docker-registry
  namespace: default
  resourceVersion: "1303"
  selfLink: /api/v1/namespaces/default/services/docker-registry
  uid: 9523c8df-f4c7-11ea-97ad-000c297c3a2d
spec:
  clusterIP: 172.30.1.1
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    docker-registry: default
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
