apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2020-09-12T07:11:47Z
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "6"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: 386c8f79-f4c7-11ea-97ad-000c297c3a2d
spec:
  clusterIP: 172.30.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
