apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.openshift.io/password: XIr1JXqbKu
    prometheus.openshift.io/username: admin
    service.alpha.openshift.io/serving-cert-secret-name: router-metrics-tls
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1599894671
  creationTimestamp: 2020-09-12T07:14:24Z
  labels:
    router: router
  name: router
  namespace: default
  resourceVersion: "1447"
  selfLink: /api/v1/namespaces/default/services/router
  uid: 9617f55c-f4c7-11ea-97ad-000c297c3a2d
spec:
  clusterIP: 172.30.189.135
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-tcp
    port: 443
    protocol: TCP
    targetPort: 443
  - name: 1936-tcp
    port: 1936
    protocol: TCP
    targetPort: 1936
  selector:
    router: router
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
