apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/original-replicas: "1"
    openshift.io/deployer-pod.completed-at: 2020-09-20 04:44:44 +0000 UTC
    openshift.io/deployer-pod.created-at: 2020-09-20 04:43:26 +0000 UTC
    openshift.io/deployer-pod.name: karafarin-nodejs-3-deploy
    openshift.io/deployment-config.latest-version: "3"
    openshift.io/deployment-config.name: karafarin-nodejs
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: ""
    openshift.io/deployment.status-reason: image change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"karafarin-nodejs","namespace":"karafarin-frontend","selfLink":"/apis/apps.openshift.io/v1/namespaces/karafarin-frontend/deploymentconfigs/karafarin-nodejs","uid":"50922087-f590-11ea-b30d-000c297c3a2d","resourceVersion":"2472109","generation":11,"creationTimestamp":"2020-09-13T07:11:16Z","labels":{"app":"karafarin-nodejs"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["karafarin-nodejs"],"from":{"kind":"ImageStreamTag","namespace":"karafarin-frontend","name":"karafarin-nodejs:latest"},"lastTriggeredImage":"172.30.1.1:5000/karafarin-frontend/karafarin-nodejs@sha256:1ca35076a1a219abbecb0c568e0b795b7e1f2238660ac8608ca73f58c239280b"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"deploymentconfig":"karafarin-nodejs"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"karafarin-nodejs","deploymentconfig":"karafarin-nodejs"}},"spec":{"containers":[{"name":"karafarin-nodejs","image":"172.30.1.1:5000/karafarin-frontend/karafarin-nodejs@sha256:1ca35076a1a219abbecb0c568e0b795b7e1f2238660ac8608ca73f58c239280b","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":3,"observedGeneration":10,"replicas":1,"updatedReplicas":1,"availableReplicas":1,"unavailableReplicas":0,"details":{"message":"image change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"DockerImage","name":"172.30.1.1:5000/karafarin-frontend/karafarin-nodejs@sha256:1ca35076a1a219abbecb0c568e0b795b7e1f2238660ac8608ca73f58c239280b"}}}]},"conditions":[{"type":"Progressing","status":"True","lastUpdateTime":"2020-09-15T07:52:51Z","lastTransitionTime":"2020-09-15T07:52:48Z","reason":"NewReplicationControllerAvailable","message":"replication controller \"karafarin-nodejs-2\" successfully rolled out"},{"type":"Available","status":"True","lastUpdateTime":"2020-09-20T04:26:53Z","lastTransitionTime":"2020-09-20T04:26:53Z","message":"Deployment config has minimum availability."}],"readyReplicas":1}}
  creationTimestamp: 2020-09-20T04:43:26Z
  generation: 3
  labels:
    app: karafarin-nodejs
    openshift.io/deployment-config.name: karafarin-nodejs
  name: karafarin-nodejs-3
  namespace: karafarin-frontend
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: karafarin-nodejs
    uid: 50922087-f590-11ea-b30d-000c297c3a2d
  resourceVersion: "2481746"
  selfLink: /api/v1/namespaces/karafarin-frontend/replicationcontrollers/karafarin-nodejs-3
  uid: d29a9adc-fafb-11ea-a47b-000c297c3a2d
spec:
  replicas: 0
  selector:
    deployment: karafarin-nodejs-3
    deploymentconfig: karafarin-nodejs
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "3"
        openshift.io/deployment-config.name: karafarin-nodejs
        openshift.io/deployment.name: karafarin-nodejs-3
      creationTimestamp: null
      labels:
        app: karafarin-nodejs
        deployment: karafarin-nodejs-3
        deploymentconfig: karafarin-nodejs
    spec:
      containers:
      - image: 172.30.1.1:5000/karafarin-frontend/karafarin-nodejs@sha256:1ca35076a1a219abbecb0c568e0b795b7e1f2238660ac8608ca73f58c239280b
        imagePullPolicy: Always
        name: karafarin-nodejs
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 3
  replicas: 0
