apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
  creationTimestamp: 2020-09-22T05:55:29Z
  labels:
    app: mysql-persistent
    template: mysql-persistent-template
  name: mysql
  namespace: karafarin-backend
  resourceVersion: "2712213"
  selfLink: /api/v1/namespaces/karafarin-backend/services/mysql
  uid: 38213b4c-fc98-11ea-a47b-000c297c3a2d
spec:
  clusterIP: 172.30.116.28
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
