apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: 2020-09-26T05:56:39Z
  labels:
    app: karafarin-backend
  name: karafarin-backend-node
  namespace: karafarin-backend
  resourceVersion: "3188920"
  selfLink: /apis/route.openshift.io/v1/namespaces/karafarin-backend/routes/karafarin-backend-node
  uid: 0b32ee99-ffbd-11ea-8755-000c297c3a2d
spec:
  host: karafarin-bk.iryad.ir
  port:
    targetPort: karafarin-backend
  to:
    kind: Service
    name: karafarin-backend-node
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2020-09-26T05:56:39Z
      status: "True"
      type: Admitted
    host: karafarin-bk.iryad.ir
    routerName: router
    wildcardPolicy: None
