apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2020-09-27T00:08:47Z
  generation: 7
  name: ipg
  namespace: gooyal
  resourceVersion: "3282972"
  selfLink: /apis/apps.openshift.io/v1/namespaces/gooyal/deploymentconfigs/ipg
  uid: 9d36e257-0055-11eb-8755-000c297c3a2d
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: ipg
    deploymentconfig: ipg
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: ipg
        deploymentconfig: ipg
    spec:
      containers:
      - env:
        - name: DEBUG
          value: "True"
        - name: DB_NAME
          value: ipg
        - name: DB_USER
          value: userVRB
        - name: DB_PASSWORD
          value: w3av3YhbCm7XBhpR
        - name: DB_HOST
          value: ipg-mysql.gooyal.svc
        - name: OAUTH2_SERVICE_CLIENT_ID
        - name: OAUTH2_SERVICE_CLIENT_SECRET
        - name: BASE_ACCOUNTS_URL
          value: http://accounts.gooyal.svc
        - name: BASE_NOTIFICATION_URL
        - name: PACKPAY_SERVICE_CODE
          value: "955"
        - name: PACKPAY_CLIENT_ID
          value: YUDsn70MA0hRl0H7FCPK
        - name: PACKPAY_CLIENT_SECRET
          value: cCOLQ2sGzkiUcShhBrvNTKOqpzIUBT
        - name: PACKPAY_REFRESH_TOKEN
          value: 07bcb982-07d9-4315-b2b0-43ba13987a6c
        image: 172.30.1.1:5000/gooyal/ipg@sha256:451ead3f49e32d903a7e2ca76b5c7efdce1a857f04e7cb2c05ec3ad026980643
        imagePullPolicy: Always
        name: gooyal
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - gooyal
      from:
        kind: ImageStreamTag
        name: ipg:latest
        namespace: gooyal
      lastTriggeredImage: 172.30.1.1:5000/gooyal/ipg@sha256:451ead3f49e32d903a7e2ca76b5c7efdce1a857f04e7cb2c05ec3ad026980643
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-09-27T00:19:30Z
    lastUpdateTime: 2020-09-27T00:19:30Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2020-09-27T00:19:31Z
    lastUpdateTime: 2020-09-27T00:19:33Z
    message: replication controller "ipg-4" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 4
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
