apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: 2020-09-26T23:22:01Z
  name: accounts
  namespace: gooyal
  resourceVersion: "3277494"
  selfLink: /apis/route.openshift.io/v1/namespaces/gooyal/routes/accounts
  uid: 14fef35b-004f-11eb-8755-000c297c3a2d
spec:
  host: accounts.gooyal.com
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: accounts
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2020-09-26T23:22:02Z
      status: "True"
      type: Admitted
    host: accounts.gooyal.com
    routerName: router
    wildcardPolicy: None
