apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kube-dns","namespace":"kube-dns"},"spec":{"clusterIP":"172.30.0.2","ports":[{"name":"dns-udp","port":53,"protocol":"UDP"},{"name":"dns-tcp","port":53,"protocol":"TCP"}],"selector":{"k8s-app":"kube-dns"}}}
  creationTimestamp: 2020-09-12T07:11:56Z
  name: kube-dns
  namespace: kube-dns
  resourceVersion: "300"
  selfLink: /api/v1/namespaces/kube-dns/services/kube-dns
  uid: 3df392e6-f4c7-11ea-97ad-000c297c3a2d
spec:
  clusterIP: 172.30.0.2
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
