apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
    service.alpha.openshift.io/serving-cert-secret-name: webconsole-serving-cert
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1599894671
  creationTimestamp: 2020-09-12T07:14:46Z
  labels:
    app: openshift-web-console
  name: webconsole
  namespace: openshift-web-console
  resourceVersion: "1984"
  selfLink: /api/v1/namespaces/openshift-web-console/services/webconsole
  uid: a3944e8b-f4c7-11ea-97ad-000c297c3a2d
spec:
  clusterIP: 172.30.110.180
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    webconsole: "true"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
