apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/original-replicas: "1"
    openshift.io/deployer-pod.completed-at: 2020-09-26 23:36:11 +0000 UTC
    openshift.io/deployer-pod.created-at: 2020-09-26 23:36:03 +0000 UTC
    openshift.io/deployer-pod.name: accounts-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: accounts
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"accounts","namespace":"karafarin-backend","selfLink":"/apis/apps.openshift.io/v1/namespaces/karafarin-backend/deploymentconfigs/accounts","uid":"f6572209-0050-11eb-8755-000c297c3a2d","resourceVersion":"3278766","generation":3,"creationTimestamp":"2020-09-26T23:35:29Z"},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["gooyal"],"from":{"kind":"ImageStreamTag","namespace":"karafarin-backend","name":"karafarin-accounts:latest"},"lastTriggeredImage":"172.30.1.1:5000/karafarin-backend/karafarin-accounts@sha256:e0346314c2c2dba934f8c7b72879b2261ebd4febf8d9ad87754959b9cd4035ed"}},{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"accounts","deploymentconfig":"accounts"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"accounts","deploymentconfig":"accounts"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"containers":[{"name":"gooyal","image":"172.30.1.1:5000/karafarin-backend/karafarin-accounts@sha256:e0346314c2c2dba934f8c7b72879b2261ebd4febf8d9ad87754959b9cd4035ed","ports":[{"containerPort":8000,"protocol":"TCP"}],"env":[{"name":"DEBUG","value":"True"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":2,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2020-09-26T23:35:29Z","lastTransitionTime":"2020-09-26T23:35:29Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: 2020-09-26T23:36:03Z
  generation: 3
  labels:
    openshift.io/deployment-config.name: accounts
  name: accounts-1
  namespace: karafarin-backend
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: accounts
    uid: f6572209-0050-11eb-8755-000c297c3a2d
  resourceVersion: "3279383"
  selfLink: /api/v1/namespaces/karafarin-backend/replicationcontrollers/accounts-1
  uid: 0ab4c4ec-0051-11eb-a47b-000c297c3a2d
spec:
  replicas: 0
  selector:
    app: accounts
    deployment: accounts-1
    deploymentconfig: accounts
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: accounts
        openshift.io/deployment.name: accounts-1
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: accounts
        deployment: accounts-1
        deploymentconfig: accounts
    spec:
      containers:
      - env:
        - name: DEBUG
          value: "True"
        image: 172.30.1.1:5000/karafarin-backend/karafarin-accounts@sha256:e0346314c2c2dba934f8c7b72879b2261ebd4febf8d9ad87754959b9cd4035ed
        imagePullPolicy: Always
        name: gooyal
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 3
  replicas: 0
