apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/original-replicas: "1"
    openshift.io/deployer-pod.completed-at: 2020-09-26 11:56:13 +0000 UTC
    openshift.io/deployer-pod.created-at: 2020-09-26 11:56:01 +0000 UTC
    openshift.io/deployer-pod.name: karafarin-backend-54-deploy
    openshift.io/deployment-config.latest-version: "54"
    openshift.io/deployment-config.name: karafarin-backend
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: ""
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"karafarin-backend","namespace":"karafarin-backend","selfLink":"/apis/apps.openshift.io/v1/namespaces/karafarin-backend/deploymentconfigs/karafarin-backend","uid":"ede3f17e-f7ec-11ea-b30d-000c297c3a2d","resourceVersion":"3219995","generation":55,"creationTimestamp":"2020-09-16T07:19:16Z","labels":{"app":"karafarin-backend"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["karafarin-backend"],"from":{"kind":"ImageStreamTag","namespace":"karafarin-backend","name":"karafarin-backend:latest"},"lastTriggeredImage":"172.30.1.1:5000/karafarin-backend/karafarin-backend@sha256:94c2b880890bc660a072864f18652c5cb684bf698ef2e82df65d65e7392bfa82"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"app":"karafarin-backend","deploymentconfig":"karafarin-backend"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"karafarin-backend","deploymentconfig":"karafarin-backend"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"containers":[{"name":"karafarin-backend","image":"172.30.1.1:5000/karafarin-backend/karafarin-backend@sha256:94c2b880890bc660a072864f18652c5cb684bf698ef2e82df65d65e7392bfa82","ports":[{"containerPort":8000,"protocol":"TCP"}],"env":[{"name":"DATABASE_URL","value":"postgresql.karafarin-backend.svc"},{"name":"DB_NAME","value":"karafarini-backend"},{"name":"DB_USER","value":"back_user"},{"name":"DB_USER_PASS","value":"cfDxk66vLSyxFnQ"},{"name":"DATABASE_URL","value":"psql://back_user:cfDxk66vLSyxFnQ@postgresql.karafarin-backend.svc:5432/karafarini-backend"},{"name":"CLIENT_ID","value":"eI9NPrzpObBLuWzGFgNpE50FWl7PstFhxw2BgfTr"},{"name":"CLIENT_SECRET","value":"0r9dF8HUQvKmhqm2BehTstZC0JyRiKnGBOJJmdI7MPqr9qHsFYijUxELWyOJ2QPn5IGtOmNzPwfXr5AYNogl6fRqdU5QPGPjgi2AGZce4L29M9ONFMzmTxef7qL0fLs1"},{"name":"BASE_NOTIFICATION_URL"},{"name":"DB_PASSWORD","value":"cfDxk66vLSyxFnQ"},{"name":"DB_HOST","value":"postgresql.karafarin-backend.svc"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":54,"observedGeneration":54,"replicas":1,"updatedReplicas":1,"availableReplicas":0,"unavailableReplicas":1,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Progressing","status":"True","lastUpdateTime":"2020-09-26T11:51:14Z","lastTransitionTime":"2020-09-26T11:51:10Z","reason":"NewReplicationControllerAvailable","message":"replication controller \"karafarin-backend-53\" successfully rolled out"},{"type":"Available","status":"False","lastUpdateTime":"2020-09-26T11:51:31Z","lastTransitionTime":"2020-09-26T11:51:31Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: 2020-09-26T11:56:01Z
  generation: 3
  labels:
    app: karafarin-backend
    openshift.io/deployment-config.name: karafarin-backend
  name: karafarin-backend-54
  namespace: karafarin-backend
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: karafarin-backend
    uid: ede3f17e-f7ec-11ea-b30d-000c297c3a2d
  resourceVersion: "3220145"
  selfLink: /api/v1/namespaces/karafarin-backend/replicationcontrollers/karafarin-backend-54
  uid: 3f6055e3-ffef-11ea-a47b-000c297c3a2d
spec:
  replicas: 0
  selector:
    app: karafarin-backend
    deployment: karafarin-backend-54
    deploymentconfig: karafarin-backend
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "54"
        openshift.io/deployment-config.name: karafarin-backend
        openshift.io/deployment.name: karafarin-backend-54
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: karafarin-backend
        deployment: karafarin-backend-54
        deploymentconfig: karafarin-backend
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql.karafarin-backend.svc
        - name: DB_NAME
          value: karafarini-backend
        - name: DB_USER
          value: back_user
        - name: DB_USER_PASS
          value: cfDxk66vLSyxFnQ
        - name: DATABASE_URL
          value: psql://back_user:cfDxk66vLSyxFnQ@postgresql.karafarin-backend.svc:5432/karafarini-backend
        - name: CLIENT_ID
          value: eI9NPrzpObBLuWzGFgNpE50FWl7PstFhxw2BgfTr
        - name: CLIENT_SECRET
          value: 0r9dF8HUQvKmhqm2BehTstZC0JyRiKnGBOJJmdI7MPqr9qHsFYijUxELWyOJ2QPn5IGtOmNzPwfXr5AYNogl6fRqdU5QPGPjgi2AGZce4L29M9ONFMzmTxef7qL0fLs1
        - name: BASE_NOTIFICATION_URL
        - name: DB_PASSWORD
          value: cfDxk66vLSyxFnQ
        - name: DB_HOST
          value: postgresql.karafarin-backend.svc
        image: 172.30.1.1:5000/karafarin-backend/karafarin-backend@sha256:94c2b880890bc660a072864f18652c5cb684bf698ef2e82df65d65e7392bfa82
        imagePullPolicy: Always
        name: karafarin-backend
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 3
  replicas: 0
