apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    openshift.io/deployer-pod.completed-at: 2020-09-27 07:25:28 +0000 UTC
    openshift.io/deployer-pod.created-at: 2020-09-27 07:14:58 +0000 UTC
    openshift.io/deployer-pod.name: notifications-4-deploy
    openshift.io/deployment-config.latest-version: "4"
    openshift.io/deployment-config.name: notifications
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/deployment.status-reason: image change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"notifications","namespace":"karafarin-backend","selfLink":"/apis/apps.openshift.io/v1/namespaces/karafarin-backend/deploymentconfigs/notifications","uid":"8a9e44b6-0086-11eb-8755-000c297c3a2d","resourceVersion":"3316748","generation":6,"creationTimestamp":"2020-09-27T05:59:01Z"},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["karafarin-backend"],"from":{"kind":"ImageStreamTag","namespace":"karafarin-backend","name":"karafarin-notifications:latest"},"lastTriggeredImage":"172.30.1.1:5000/karafarin-backend/karafarin-notifications@sha256:24f61beb2ec8af5876e408f1052b4777dd09945c34218671f646b5a60674bff6"}},{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"notifications","deploymentconfig":"notifications"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"notifications","deploymentconfig":"notifications"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"containers":[{"name":"karafarin-backend","image":"172.30.1.1:5000/karafarin-backend/karafarin-notifications@sha256:24f61beb2ec8af5876e408f1052b4777dd09945c34218671f646b5a60674bff6","ports":[{"containerPort":8000,"protocol":"TCP"}],"env":[{"name":"DEBUG","value":"True"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":4,"observedGeneration":5,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"image change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"DockerImage","name":"172.30.1.1:5000/karafarin-backend/karafarin-notifications@sha256:24f61beb2ec8af5876e408f1052b4777dd09945c34218671f646b5a60674bff6"}}}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2020-09-27T05:59:02Z","lastTransitionTime":"2020-09-27T05:59:02Z","message":"Deployment config does not have minimum availability."},{"type":"Progressing","status":"False","lastUpdateTime":"2020-09-27T06:20:29Z","lastTransitionTime":"2020-09-27T06:20:29Z","reason":"ProgressDeadlineExceeded","message":"replication controller \"notifications-3\" has failed progressing"}]}}
  creationTimestamp: 2020-09-27T07:14:55Z
  generation: 3
  labels:
    openshift.io/deployment-config.name: notifications
  name: notifications-4
  namespace: karafarin-backend
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: notifications
    uid: 8a9e44b6-0086-11eb-8755-000c297c3a2d
  resourceVersion: "3317443"
  selfLink: /api/v1/namespaces/karafarin-backend/replicationcontrollers/notifications-4
  uid: 24abb29d-0091-11eb-a47b-000c297c3a2d
spec:
  replicas: 0
  selector:
    app: notifications
    deployment: notifications-4
    deploymentconfig: notifications
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "4"
        openshift.io/deployment-config.name: notifications
        openshift.io/deployment.name: notifications-4
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: notifications
        deployment: notifications-4
        deploymentconfig: notifications
    spec:
      containers:
      - env:
        - name: DEBUG
          value: "True"
        image: 172.30.1.1:5000/karafarin-backend/karafarin-notifications@sha256:24f61beb2ec8af5876e408f1052b4777dd09945c34218671f646b5a60674bff6
        imagePullPolicy: Always
        name: karafarin-backend
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 3
  replicas: 0
