apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: 2020-09-26T23:27:41Z
  name: accounts
  namespace: karafarin-backend
  resourceVersion: "3346496"
  selfLink: /apis/build.openshift.io/v1/namespaces/karafarin-backend/buildconfigs/accounts
  uid: df455d4c-004f-11eb-8755-000c297c3a2d
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: karafarin-accounts:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      ###########
      # BUILDER #
      ###########

      # pull official base image

      FROM debian:buster
      USER root
      ENV BRANCH=master
      ENV BASE_DIR=/opt
      ENV APP_DIR=/opt/app
      ENV APP_USER=app_user
      ENV PROJECT_NAME=app

      #RUN echo "deb http://deb.debian.org/debian buster main contrib non-free" >> /etc/apt/sources.list
      #RUN echo "deb http://deb.debian.org/debian-security/ buster/updates main contrib non-free" >> /etc/apt/sources.list
      #RUN echo "deb http://deb.debian.org/debian buster-updates main contrib non-free" >> /etc/apt/sources.list
      #RUN apt update && apt install git build-essential libssl-dev libffi-dev python3-dev python3-pip libcrypto++-dev lsb-release -y
      #RUN apt update && apt install default-libmysqlclient-dev -y


      WORKDIR $BASE_DIR
      RUN git clone https://pullerutil:jjishu337aanoAAdd@mgit.mparsict.com/sayyid.hamid.mahdavi/gooyal_accounts.git $APP_DIR
      WORKDIR $APP_DIR
      RUN git checkout $BRANCH

      RUN pip3 install --upgrade pip
      RUN pip install git+https://pullerutil:jjishu337aanoAAdd@mgit.mparsict.com/utils/service_clients.git
      RUN pip install -r requirements.txt

      RUN adduser $APP_USER && usermod -aG $APP_USER $APP_USER

      #RUN python3 manage.py collectstatic
      #RUN python manage.py migrate

      RUN mkdir $APP_DIR/static
      RUN mkdir $APP_DIR/media
      RUN mkdir $APP_DIR/logs
      RUN chmod -R 777 /opt/app  && \
          chown $APP_USER:0 /opt/app -R && \
          chmod +x /opt/app -R

      USER $APP_USER

      EXPOSE 8000 8000
      CMD ["bash", "run.sh"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base:mysql-client
        namespace: gooyal
    type: Docker
  triggers:
  - type: ConfigChange
status:
  lastVersion: 3
