apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: 2020-09-22T05:59:58Z
  labels:
    build: karafarin-ipg
  name: karafarin-ipg
  namespace: karafarin-backend
  resourceVersion: "3194668"
  selfLink: /apis/build.openshift.io/v1/namespaces/karafarin-backend/buildconfigs/karafarin-ipg
  uid: d8b730e9-fc98-11ea-8755-000c297c3a2d
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: karafarin-ipg:latest
  postCommit: {}
  resources:
    limits:
      cpu: "1"
      memory: 1000Mi
  runPolicy: Serial
  source:
    dockerfile: |-
      ###########
      # BUILDER #
      ###########

      # pull official base image

      FROM debian:buster
      USER root
      ENV BRANCH=develop
      ENV BASE_DIR=/opt
      ENV APP_DIR=/opt/app
      ENV APP_USER=app_user
      ENV PROJECT_NAME=app

      #RUN echo "deb http://deb.debian.org/debian buster main contrib non-free" >> /etc/apt/sources.list
      #RUN echo "deb http://deb.debian.org/debian-security/ buster/updates main contrib non-free" >> /etc/apt/sources.list
      #RUN echo "deb http://deb.debian.org/debian buster-updates main contrib non-free" >> /etc/apt/sources.list
      #RUN apt update && apt install git build-essential libssl-dev libffi-dev python3-dev python3-pip default-libmysqlclient-dev -y

      WORKDIR $BASE_DIR
      RUN git clone https://pullerutil:jjishu337aanoAAdd@mgit.mparsict.com/sayyid.hamid.mahdavi/gooyal_ipg.git $APP_DIR
      WORKDIR $APP_DIR
      # RUN git checkout $BRANCH

      RUN pip3 install --upgrade pip
      RUN pip install git+https://pullerutil:jjishu337aanoAAdd@mgit.mparsict.com/utils/service_clients.git
      RUN pip install -r requirements.txt

      RUN adduser $APP_USER && usermod -aG $APP_USER $APP_USER
      RUN mkdir $APP_DIR/static
      RUN mkdir $APP_DIR/media

      #RUN python3 manage.py collectstatic
      #RUN python manage.py migrate

      RUN mkdir $APP_DIR/logs
      RUN chmod -R 777 /opt/app  && \
          chown $APP_USER:0 /opt/app -R && \
          chmod +x /opt/app -R

      USER $APP_USER

      EXPOSE 8000 8000

      CMD ["bash", "run.sh"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      env:
      - name: PROJECT_NAME
        value: app
      - name: SECRET_KEY
        value: w%97bq=zho5c=n0%lpz2il+^bznp6b+za+$04^g675me5u0%e4
      - name: DB_NAME
        value: ipg
      - name: DB_USER
      from:
        kind: ImageStreamTag
        name: karafarin-ipg:pre-1
    type: Docker
  successfulBuildsHistoryLimit: 20
  triggers:
  - type: ConfigChange
status:
  lastVersion: 20
