apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: 2020-09-27T05:06:18Z
  name: notifications
  namespace: karafarin-backend
  resourceVersion: "3315874"
  selfLink: /apis/build.openshift.io/v1/namespaces/karafarin-backend/buildconfigs/notifications
  uid: 2d14e647-007f-11eb-8755-000c297c3a2d
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: karafarin-notifications:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      ###########
      # BUILDER #
      ###########

      # pull official base image

      FROM debian:buster
      USER root
      ENV BRANCH=develop
      ENV BASE_DIR=/opt
      ENV APP_DIR=/opt/app
      ENV APP_USER=app_user
      ENV PROJECT_NAME=app

      #RUN echo "deb http://deb.debian.org/debian buster main contrib non-free" >> /etc/apt/sources.list
      #RUN echo "deb http://deb.debian.org/debian-security/ buster/updates main contrib non-free" >> /etc/apt/sources.list
      #RUN echo "deb http://deb.debian.org/debian buster-updates main contrib non-free" >> /etc/apt/sources.list
      #RUN apt update && apt install git build-essential libssl-dev libffi-dev python3-dev python3-pip default-libmysqlclient-dev -y
      RUN apt install libcrypto++-dev lsb-release -y

      WORKDIR $BASE_DIR
      RUN git clone --single-branch --branch $BRANCH https://pullerutil:jjishu337aanoAAdd@mgit.mparsict.com/services/notification_service.git $APP_DIR
      WORKDIR $APP_DIR

      RUN pip3 install --upgrade pip
      RUN pip install git+https://pullerutil:jjishu337aanoAAdd@mgit.mparsict.com/utils/mp-logging-helper.git
      RUN pip install git+https://pullerutil:jjishu337aanoAAdd@mgit.mparsict.com/utils/mp-model-helper.git
      RUN pip install git+https://pullerutil:jjishu337aanoAAdd@mgit.mparsict.com/utils/mp-api-helper.git
      RUN pip install git+https://pullerutil:jjishu337aanoAAdd@mgit.mparsict.com/utils/service_clients.git
      RUN pip install -r requirements.txt

      RUN adduser $APP_USER && usermod -aG $APP_USER $APP_USER

      #RUN python3 manage.py collectstatic
      #RUN python manage.py migrate

      RUN mkdir $APP_DIR/static
      RUN mkdir $APP_DIR/media
      RUN mkdir $APP_DIR/logs
      RUN chmod -R 777 /opt/app  && \
          chown $APP_USER:0 /opt/app -R && \
          chmod +x /opt/app -R

      USER $APP_USER

      EXPOSE 8000 8000
      CMD ["bash", "run.sh"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      env:
      - name: SECRET
        value: some secret
      from:
        kind: ImageStreamTag
        name: karafarin-ipg:pre-1
      noCache: true
    type: Docker
  triggers:
  - type: ConfigChange
status:
  lastVersion: 11
