apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2020-09-22T09:40:16Z
  generation: 18
  labels:
    app: karafarin-ipg
  name: karafarin-ipg
  namespace: karafarin-backend
  resourceVersion: "3194994"
  selfLink: /apis/apps.openshift.io/v1/namespaces/karafarin-backend/deploymentconfigs/karafarin-ipg
  uid: 9f1039e9-fcb7-11ea-8755-000c297c3a2d
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: karafarin-ipg
    deploymentconfig: karafarin-ipg
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: karafarin-ipg
        deploymentconfig: karafarin-ipg
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: mysql.karafarin-backend.svc
        - name: DB_NAME
          value: ipg
        - name: DB_USER
          value: userO4V
        - name: DB_PASSWORD
          value: XKrJbB44BNOmhbDJ
        - name: OAUTH2_SERVICE_CLIENT_ID
          value: qQtiETS7boGHBEi9vQhF9bSe3IWw6RxeuQ70Eo0s
        - name: OAUTH2_SERVICE_CLIENT_SECRET
          value: 4F3SCrOLuX0sjMx1bM4RMnE7K6MhRxuRoUMCQFYgj42y7yFVcwe1DGmdEETEPDjlUzMNox7ghGLZIDMi8bYa9O1vYyDHDsUSBKB5TasHsVjAT5pxdSdou0hvYpXfALoo
        - name: BASE_NOTIFICATION_URL
        - name: BASE_ACCOUNTS_URL
          value: http://staging-services.mparsict.com
        - name: PACKPAY_SERVICE_CODE
          value: "955"
        - name: PACKPAY_CLIENT_ID
          value: YUDsn70MA0hRl0H7FCPK
        - name: PACKPAY_CLIENT_SECRET
          value: cCOLQ2sGzkiUcShhBrvNTKOqpzIUBT
        - name: PACKPAY_REFRESH_TOKEN
          value: 07bcb982-07d9-4315-b2b0-43ba13987a6c
        image: 172.30.1.1:5000/karafarin-backend/karafarin-ipg@sha256:b0a7bad65a45c9b808064e46ff17c2bcf37b131bedae4ea8a118786ac927331e
        imagePullPolicy: Always
        name: karafarin-backend
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - karafarin-backend
      from:
        kind: ImageStreamTag
        name: karafarin-ipg:latest
        namespace: karafarin-backend
      lastTriggeredImage: 172.30.1.1:5000/karafarin-backend/karafarin-ipg@sha256:b0a7bad65a45c9b808064e46ff17c2bcf37b131bedae4ea8a118786ac927331e
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-09-22T10:48:19Z
    lastUpdateTime: 2020-09-22T10:48:19Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2020-09-26T07:05:22Z
    lastUpdateTime: 2020-09-26T07:05:25Z
    message: replication controller "karafarin-ipg-16" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: 172.30.1.1:5000/karafarin-backend/karafarin-ipg@sha256:b0a7bad65a45c9b808064e46ff17c2bcf37b131bedae4ea8a118786ac927331e
      type: ImageChange
    message: image change
  latestVersion: 16
  observedGeneration: 18
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
